# .github/workflows/ci.yml
name: Playwright QA Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run tests
        run: |
          pytest tests/ -n auto --html=reports/report.html --self-contained-html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: reports/report.html

      # (Opcional) Allure
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: reports/allure-results
